GET http://localhost:4000/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NGVkYmFlZjI2MzI2NTkwYzEzZDU0YiIsIm5hbWUiOiJMYWxpbnkiLCJpYXQiOjE2OTk4ODU5NTV9._UL5FaHTCxe5zyWdrF1fSI1SEfdQQB0y2YFK_VSIeGY

###

GET http://localhost:4000/users/654edbaef26326590c13d54b HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NGVkYmFlZjI2MzI2NTkwYzEzZDU0YiIsIm5hbWUiOiJMYWxpbnkiLCJpYXQiOjE2OTk4ODU5NTV9._UL5FaHTCxe5zyWdrF1fSI1SEfdQQB0y2YFK_VSIeGY

###

PATCH http://localhost:4000/users/654edbaef26326590c13d54b HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NGVkYmFlZjI2MzI2NTkwYzEzZDU0YiIsIm5hbWUiOiJMYWxpbnkiLCJpYXQiOjE2OTk4ODU5NTV9._UL5FaHTCxe5zyWdrF1fSI1SEfdQQB0y2YFK_VSIeGY

{
	"name": "Laliny Perezini"
}

###

DELETE http://localhost:4000/users/654edbaef26326590c13d54b HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NGVkYmFlZjI2MzI2NTkwYzEzZDU0YiIsIm5hbWUiOiJMYWxpbnkiLCJpYXQiOjE2OTk4ODU5NTV9._UL5FaHTCxe5zyWdrF1fSI1SEfdQQB0y2YFK_VSIeGY

###

POST http://localhost:4000/auth/register HTTP/1.1
Content-Type: application/json

{
	"name": "Laliny",
	"email": "laliny@test.com",
	"password": "pass_test"
}

###

POST http://localhost:4000/auth/login HTTP/1.1
Content-Type: application/json

{
	"email": "laliny@test.com",
	"password": "pass_test"
}

###